require("clay.plugins-setup")
require("clay.core.options")
require("clay.core.keymaps")
require("clay.core.colorscheme")
require("clay.plugins.nvim-tree")
require("clay.plugins.lualine")
require("clay.plugins.telescope")
require("clay.plugins.nvim-cmp")
require("clay.plugins.lsp.mason")
require("clay.plugins.lsp.lspsaga")
require("clay.plugins.lsp.lspconfig")
require("clay.plugins.lsp.null-ls")
require("clay.plugins.autoparis")
require("clay.plugins.treesitter")
require("clay.plugins.gitsigns")

